name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/hamsterkombatbot:latest

      - name: Create .env file
        run: |
          echo "API_ID=12345" > .env
          echo "API_HASH=12345" >> .env

      - name: Run container
        run: |
          docker compose up -d
          docker compose ps

      - name: Check container status
        run: |
          container_status=$(docker compose ps --status running --format "table {{.Name}}\t{{.Image}}\t{{.Command}}\t{{.Service}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Ports}}")
          echo "$container_status"
          if echo "$container_status" | grep -q "Up"; then
            echo "Container is running. Proceeding."
          else
            echo "Container is not running. Exiting."
            exit 1
          fi

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/hamsterkombatbot:latest